site_name: Unturned 3 Knowledgebase
site_url: https://unturned.info
repo_name: unturned-3-knowledgebase
repo_url: https://github.com/Unturned-Official-Discord/unturned-3-knowledgebase
site_description: >-
  Documentation for various features of Unturned 3.0
  Including modding, server hosting, and more.
theme:
  name: material
  logo: img/Unturned_Logo.png
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    # options: default, slate, preference
    scheme: preference
    primary: indigo
    # accent: green
  features:
    - tabs
    - instant
extra:
  social:
    - icon: fontawesome/brands/steam
      link: https://store.steampowered.com/app/304930/Unturned/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/unturned 
      name: Unturned Official Discord
    - icon: fontawesome/brands/discourse
      link: https://forum.smartlydressedgames.com
      name: SDG Forums
    - icon: fontawesome/brands/wordpress  
      link: https://blog.smartlydressedgames.com
      name: SDG Blog
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      provider: 'github'
      repo: 'unturned-3-knowledgebase'
  - toc:
      permalink: true
plugins:
  - git-revision-date-localized:
      type: date
  - search
  
